/* Do NOT modify this file! It has been autogenerated by the tools.*/
/* File created by HLSL wrapper generator version 0.5 on Tuesday, May 15th, at 19-50-36 */

#pragma once

RX_PROCESS_VERTEX_TYPE_WITH_MACRO( Vertex_P3f )
RX_PROCESS_VERTEX_TYPE_WITH_MACRO( Vertex_P3f_TEX2f )
RX_PROCESS_VERTEX_TYPE_WITH_MACRO( Vertex_P3f_TEX2f_N4Ub_T4Ub )
RX_PROCESS_VERTEX_TYPE_WITH_MACRO( Vertex_P3f_TEX2f_COL4Ub )

//--------------------------------------------------------------//
//				End Of File.									//
//--------------------------------------------------------------//
