// This file is autogenerated! Do NOT modify it by hand!
// Resource GUIDs extracted from package 'meshes'.
//
#pragma once

// file: '?', type: 'Mesh', size: 256
#define Quad 		 0x43A30000
// file: '?', type: 'Mesh', size: 876
#define Box 		 0x43A30001
// file: '?', type: 'Mesh', size: 1966212
#define highly_tesselated_sphere_3ds 		 0x43A30002
// file: '?', type: 'Mesh', size: 704
#define huge_pyramid_3DS 		 0x43A30003
// file: '?', type: 'Mesh', size: 948
#define skewed_cube_3DS 		 0x43A30004

