// This file is autogenerated! Do NOT modify it by hand!
// Resource GUIDs from package 'textures'
//
#pragma once

// file: 'D:/dev/Media/textures/gothic_stone.d.png', type: 'Texture', size: 141005
#define gothic_stone_d_png 		 0x63A80000
// file: 'D:/dev/Media/textures/gothic_stone.n.png', type: 'Texture', size: 118026
#define gothic_stone_n_png 		 0x63A80001
// file: 'D:/dev/Media/textures/grass1_d.dds', type: 'Texture', size: 2796344
#define grass1_d_dds 		 0x63A80002
// file: 'D:/dev/Media/textures/grass1_n.dds', type: 'Texture', size: 699192
#define grass1_n_dds 		 0x63A80003
// file: 'D:/dev/Media/textures/ground_earth_d.dds', type: 'Texture', size: 699192
#define ground_earth_d_dds 		 0x63A80004
// file: 'D:/dev/Media/textures/ground_earth_n.dds', type: 'Texture', size: 699192
#define ground_earth_n_dds 		 0x63A80005
// file: 'D:/dev/Media/textures/laser_pointer_sprite.bmp', type: 'Texture', size: 48822
#define laser_pointer_sprite_bmp 		 0x63A80006
// file: 'D:/dev/Media/textures/metal_panels_d.png', type: 'Texture', size: 490310
#define metal_panels_d_png 		 0x63A80007
// file: 'D:/dev/Media/textures/metal_panels_n.png', type: 'Texture', size: 192404
#define metal_panels_n_png 		 0x63A80008
// file: 'D:/dev/Media/textures/metal_plate_d.jpg', type: 'Texture', size: 100253
#define metal_plate_d_jpg 		 0x63A80009
// file: 'D:/dev/Media/textures/metal_plate_n.jpg', type: 'Texture', size: 188027
#define metal_plate_n_jpg 		 0x63A8000A
// file: 'D:/dev/Media/textures/metal_tile_d.png', type: 'Texture', size: 1407308
#define metal_tile_d_png 		 0x63A8000B
// file: 'D:/dev/Media/textures/metal_tile_n.png', type: 'Texture', size: 845963
#define metal_tile_n_png 		 0x63A8000C
// file: 'D:/dev/Media/textures/rockwall_classic_d.jpg', type: 'Texture', size: 118322
#define rockwall_classic_d_jpg 		 0x63A8000D
// file: 'D:/dev/Media/textures/rockwall_classic_h.bmp', type: 'Texture', size: 66614
#define rockwall_classic_h_bmp 		 0x63A8000E
// file: 'D:/dev/Media/textures/rockwall_classic_n.png', type: 'Texture', size: 129862
#define rockwall_classic_n_png 		 0x63A8000F
// file: 'D:/dev/Media/textures/stained_glass_da.dds', type: 'Texture', size: 87536
#define stained_glass_da_dds 		 0x63A80010
// file: 'D:/dev/Media/textures/stained_glass_n.dds', type: 'Texture', size: 174904
#define stained_glass_n_dds 		 0x63A80011

