// This file is autogenerated! Do NOT modify it by hand!
// Resource GUIDs extracted from package 'Engine'.
//
#pragma once

// file: 'R:/TheCansinDeferredRendererFinalSourceCode/TheCansinDeferredRenderer/TheCansinDeferredRendererContent/RandomNormals.png', type: 'Texture', size: 26262
#define RandomNormals_png 		 0x78E60000

